# Generated by Django 4.2 on 2023-04-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='follower',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='following',
            field=models.IntegerField(),
        ),
    ]
