# Generated by Django 4.2 on 2023-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_instagram_follower_alter_instagram_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='follower',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='following',
            field=models.CharField(max_length=30),
        ),
    ]
